### ISSUE TITLE
Consistent error

### ISSUE THREAD

**Issue by mauzao9** [mishalhossin/Discord-AI-Chatbot#107]
Be it the Replit setup or docker, both are running into the same jinxed boot crash:

```discordbot | Traceback (most recent call last):
discordbot |   File "/usr/local/lib/python3.8/site-packages/requests_toolbelt/_compat.py", line 48, in <module>
discordbot |     from requests.packages.urllib3.contrib import appengine as gaecontrib
discordbot | ImportError: cannot import name 'appengine' from 'requests.packages.urllib3.contrib' (/usr/local/lib/python3.8/site-packages/urllib3/contrib/__init__.py)
discordbot |
discordbot | During handling of the above exception, another exception occurred:
discordbot |
discordbot | Traceback (most recent call last):
discordbot |   File "main.py", line 13, in <module>
discordbot |     from imaginepy import AsyncImagine, Style, Ratio
discordbot |   File "/usr/local/lib/python3.8/site-packages/imaginepy/__init__.py", line 1, in <module>
discordbot |     from .sync_imagine import Imagine
discordbot |   File "/usr/local/lib/python3.8/site-packages/imaginepy/sync_imagine.py", line 3, in <module>
discordbot |     from requests_toolbelt.multipart.encoder import MultipartEncoder
discordbot |   File "/usr/local/lib/python3.8/site-packages/requests_toolbelt/__init__.py", line 12, in <module>
discordbot |     from .adapters import SSLAdapter, SourceAddressAdapter
discordbot |   File "/usr/local/lib/python3.8/site-packages/requests_toolbelt/adapters/__init__.py", line 12, in <module>
discordbot |     from .ssl import SSLAdapter
discordbot |   File "/usr/local/lib/python3.8/site-packages/requests_toolbelt/adapters/ssl.py", line 16, in <module>
discordbot |     from .._compat import poolmanager
discordbot |   File "/usr/local/lib/python3.8/site-packages/requests_toolbelt/_compat.py", line 50, in <module>
discordbot |     from urllib3.contrib import appengine as gaecontrib
discordbot | ImportError: cannot import name 'appengine' from 'urllib3.contrib' (/usr/local/lib/python3.8/site-packages/urllib3/contrib/__init__.py)
```

**Comment by mishalhossin** [comment]
Just run this in `Shell` then click run

```
pip install --upgrade requests-toolbelt urllib3
```

**Comment by mauzao9** [comment]
> Just run this in `Shell` then click run
> 
> ```
> pip install --upgrade requests-toolbelt urllib3
> ```

No luck with that, that's one I tried googling the specific error at first but same outcome running the docker.

On the replit you linked, if you config the tokens and run it, it is also running into the same error on their side.

**Comment by mishalhossin** [comment]
okay fixed now
