### ISSUE TITLE
i got this error 

### ISSUE THREAD

**Issue by wanshade** [mishalhossin/Discord-AI-Chatbot#111]
ubuntu@VM-0-5-ubuntu:~/Discord-AI-Chatbot$ python3 main.py
2023-05-31 17:39:57 INFO     discord.client logging in using static token
2023-05-31 17:39:58 INFO     discord.gateway Shard ID None has connected to Gateway (Session ID: 35a79c17e8927cd3e5be6834addf5ab8).
2023-05-31 17:40:01 ERROR    discord.client Ignoring exception in on_ready
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/ubuntu/Discord-AI-Chatbot/main.py", line 59, in on_ready
    await bot.tree.sync()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/app_commands/tree.py", line 1067, in sync
    data = await self._http.bulk_upsert_global_commands(self.client.application_id, payload=payload)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/discord/http.py", line 744, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 400 Bad Request (error code: 30034): Max number of daily application command creates has been reached (200)

**Comment by mishalhossin** [comment]
Discord imposes this limit to prevent abuse and ensure a fair usage policy. To resolve this issue, you have a few options:

1. Wait until the next day: The limit is reset every day, so you can try running the command again after the daily reset.

2. Remove existing application commands: If you have previously created application commands that are no longer needed, you can remove them to free up space for new commands. You can do this through the Discord developer portal or using the Discord API.

3. Upgrade your bot: Discord offers a feature called "Bot Verification" that provides higher limits and additional benefits. If your bot requires a large number of application commands or has a significant user base, upgrading to Bot Verification may be a suitable solution.
