### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by mishalhossin** [mishalhossin/Discord-AI-Chatbot#128]
`Task exception was never retrieved
future: <Task finished name='Task-36' coro=<on_message.<locals>.generate_response_in_thread() done, defined at /workspace/Discord-AI-Chatbot/main.py:383> exception=IndexError('list index out of range')>
Traceback (most recent call last):
  File "/workspace/Discord-AI-Chatbot/main.py", line 386, in generate_response_in_thread
    response = await generate_response(prompt)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Discord-AI-Chatbot/main.py", line 142, in generate_response
    response = await aiassist.Completion.create(prompt=prompt)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Discord-AI-Chatbot/model/aiassist.py", line 28, in create
    response = Completion.__load_json(content)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/Discord-AI-Chatbot/model/aiassist.py", line 34, in __load_json
    split = decode_content.rsplit("\n", 1)[1]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range`

**Comment by mishalhossin** [comment]
The error seems to be happening in the __load_json method of the aiassist.py file. It appears that the code is trying to split a string using the rsplit function and access the second element of the resulting list, but there might not be a second element in the list.

**Comment by mishalhossin** [comment]
Fixed in https://github.com/mishalhossin/Discord-AI-Chatbot/commit/14d6bb88100ca07e7b9bc8092a3186b440ec6cb3
