### ISSUE TITLE
Please help

### ISSUE THREAD

**Issue by Peny22888** [mishalhossin/Discord-AI-Chatbot#129]
Traceback (most recent call last):
  File "C:\Users\ratat\OneDrive\Desktop\Discord-AI-Chatbot-main\main.py", line 26, in <module>
    config = yaml.safe_load(config_file)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ratat\AppData\Local\Programs\Python\Python311\Lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ratat\AppData\Local\Programs\Python\Python311\Lib\site-packages\yaml\__init__.py", line 79, in load
    loader = Loader(stream)
             ^^^^^^^^^^^^^^
  File "C:\Users\ratat\AppData\Local\Programs\Python\Python311\Lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "C:\Users\ratat\AppData\Local\Programs\Python\Python311\Lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "C:\Users\ratat\AppData\Local\Programs\Python\Python311\Lib\site-packages\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()
  File "C:\Users\ratat\AppData\Local\Programs\Python\Python311\Lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ratat\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 957: character maps to <undefined>

**Comment by mishalhossin** [comment]
Will be fixed soon

**Comment by mishalhossin** [comment]
if you wanna fix it yourself rn

Replace line 25 to 26
```
with open('config.yml') as config_file:
    config = yaml.safe_load(config_file)
```
With
```
with open('config.yml', 'r', encoding='utf-8') as config_file:
    config = yaml.safe_load(config_file)

```

**Comment by Peny22888** [comment]
Thanks
