### ISSUE TITLE
Rate limited after (2-3 messages) 

### ISSUE THREAD

**Issue by enemyalert** [mishalhossin/Discord-AI-Chatbot#135]
```
ERROR:discord.client:Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/runner/Discord-AI-Chatbot/venv/lib/python3.10/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/runner/Discord-AI-Chatbot/main.py", line 400, in on_message
    search_results = await search(message.content)
  File "/home/runner/Discord-AI-Chatbot/main.py", line 244, in search
    search_query = await get_query(prompt)
  File "/home/runner/Discord-AI-Chatbot/main.py", line 227, in get_query
    response = await aiassist.Completion.create(prompt=fullprompt)
  File "/home/runner/Discord-AI-Chatbot/model/aiassist.py", line 55, in create
    response = Completion.__load_yml(content)
  File "/home/runner/Discord-AI-Chatbot/model/aiassist.py", line 63, in __load_yml
    to_json = json.loads(split[1])
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

I set GPT-4 to False, yet I got this error. I don't spam messages it suddenly stops responding after 2-3 messages.

**Comment by mishalhossin** [comment]
Fixed
