### ISSUE TITLE
json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by ItsDixie** [mishalhossin/Discord-AI-Chatbot#139]
```
Task exception was never retrieved
future: <Task finished name='Task-97' coro=<on_message.<locals>.generate_response_in_thread() done, defined at c:\Users\dixik\Desktop\Discord-AI-Chatbot\main.py:416> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>
Traceback (most recent call last):
  File "c:\Users\dixik\Desktop\Discord-AI-Chatbot\main.py", line 419, in generate_response_in_thread
    response = await generate_response(prompt)
  File "c:\Users\dixik\Desktop\Discord-AI-Chatbot\main.py", line 148, in generate_response
    response = await aiassist.Completion.create(prompt=prompt)
  File "c:\Users\dixik\Desktop\Discord-AI-Chatbot\model\aiassist.py", line 59, in create
    response = Completion.__load_json(content)
  File "c:\Users\dixik\Desktop\Discord-AI-Chatbot\model\aiassist.py", line 67, in __load_json
    to_json = json.loads(split[1])
  File "C:\Users\dixik\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\dixik\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\dixik\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
?[30;1m2023-06-11 00:02:15?[0m ?[31mERROR   ?[0m ?[35mdiscord.client?[0m Ignoring exception in on_message
?[31mTraceback (most recent call last):
  File "C:\Users\dixik\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "c:\Users\dixik\Desktop\Discord-AI-Chatbot\main.py", line 408, in on_message
    search_results = await search(message.content)
  File "c:\Users\dixik\Desktop\Discord-AI-Chatbot\main.py", line 246, in search
    search_query = await get_query(prompt)
  File "c:\Users\dixik\Desktop\Discord-AI-Chatbot\main.py", line 228, in get_query
    response = await aiassist.Completion.create(prompt=fullprompt)
  File "c:\Users\dixik\Desktop\Discord-AI-Chatbot\model\aiassist.py", line 59, in create
    response = Completion.__load_json(content)
  File "c:\Users\dixik\Desktop\Discord-AI-Chatbot\model\aiassist.py", line 67, in __load_json
    to_json = json.loads(split[1])
  File "C:\Users\dixik\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\dixik\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\dixik\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)?[0m
```
sometimes after sending message to bot it showing this error and stops reaction to any other message except loading gif
![image](https://github.com/mishalhossin/Discord-AI-Chatbot/assets/82880216/5ca920f2-c0ce-4e01-9e7f-98abbf4a6d6c)

**Comment by IntrovertedFL** [comment]
I'm getting a similar error now.

```
discordbot  | Task exception was never retrieved
discordbot  | future: <Task finished name='Task-69' coro=<on_message.<locals>.generate_response_in_thread() done, defined at /app/main.py:420> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>
discordbot  | Traceback (most recent call last):
discordbot  |   File "/app/main.py", line 423, in generate_response_in_thread
discordbot  |     response = await generate_response(prompt)
discordbot  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
discordbot  |   File "/app/main.py", line 150, in generate_response
discordbot  |     response = await aiassist.Completion.create(prompt=prompt)
discordbot  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
discordbot  |   File "/app/model/aiassist.py", line 59, in create
discordbot  |     response = Completion.__load_json(content)
discordbot  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
discordbot  |   File "/app/model/aiassist.py", line 67, in __load_json
discordbot  |     to_json = json.loads(split[1])
discordbot  |               ^^^^^^^^^^^^^^^^^^^^
discordbot  |   File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
discordbot  |     return _default_decoder.decode(s)
discordbot  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
discordbot  |   File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
discordbot  |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
discordbot  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
discordbot  |   File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
discordbot  |     raise JSONDecodeError("Expecting value", s, err.value) from None
discordbot  | json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
