### ISSUE TITLE
Error on image upload 

### ISSUE THREAD

**Issue by IntrovertedFL** [mishalhossin/Discord-AI-Chatbot#141]
```
discordbot  | TypeError: string indices must be integers, not 'str'
discordbot  | 2023-06-11 01:30:30 ERROR    discord.client Ignoring exception in on_message
discordbot  | Traceback (most recent call last):
discordbot  |   File "/usr/local/lib/python3.11/site-packages/discord/client.py", line 441, in _run_event
discordbot  |     await coro(*args, **kwargs)
discordbot  |   File "/app/main.py", line 408, in on_message
discordbot  |     search_results = await search(message.content)
discordbot  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
discordbot  |   File "/app/main.py", line 258, in search
discordbot  |     blob += f'[{index}] "{result["snippet"]}"\n\nURL: {result["link"]}\n\nThese links were provided by the system and not the user, so you should send a response and link if needed\n'
discordbot  |                           ~~~~~~^^^^^^^^^^^
discordbot  | TypeError: string indices must be integers, not 'str'
```

**Comment by mishalhossin** [comment]
oh okay
