### ISSUE TITLE
KeyError: 'choices' and Task exception was never retrieved

### ISSUE THREAD

**Issue by Visionishere** [mishalhossin/Discord-AI-Chatbot#148]
Looks like the environment variables exists...
Discord Token environment variable is valid
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000000033D49D0>
Traceback (most recent call last):
  File "C:\Users\Vision\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\Vision\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\Vision\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "C:\Users\Vision\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
[2023-06-13 20:31:49] [INFO    ] discord.client: logging in using static token
[2023-06-13 20:31:50] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 917ef1c7891031685586153a73fa9fdb).
DreamybullGPT Ran by Vision3184#7002 aka DreamybullGPT Ran by Vision3184 has connected to Discord!
Invite link: REMOVED
Task exception was never retrieved
future: <Task finished name='Task-19' coro=<on_message.<locals>.generate_response_in_thread() done, defined at C:\Users\Vision\Desktop\gpt4free-discord-main\main.py:138> exception=KeyError('choices')>
Traceback (most recent call last):
  File "C:\Users\Vision\Desktop\gpt4free-discord-main\main.py", line 140, in generate_response_in_thread
    response = await generate_response(prompt)
  File "C:\Users\Vision\Desktop\gpt4free-discord-main\utilities\ai_utils.py", line 62, in generate_response
    return response_data['choices'][0]['text']
KeyError: 'choices'
Task exception was never retrieved
future: <Task finished name='Task-25' coro=<on_message.<locals>.generate_response_in_thread() done, defined at C:\Users\Vision\Desktop\gpt4free-discord-main\main.py:138> exception=KeyError('choices')>
Traceback (most recent call last):
  File "C:\Users\Vision\Desktop\gpt4free-discord-main\main.py", line 140, in generate_response_in_thread
    response = await generate_response(prompt)
  File "C:\Users\Vision\Desktop\gpt4free-discord-main\utilities\ai_utils.py", line 62, in generate_response
    return response_data['choices'][0]['text']
KeyError: 'choices'

**Comment by Visionishere** [comment]
The prompt I used is custom, and has LOTS of info about Dreamybull.

**Comment by mishalhossin** [comment]
> The prompt I used is custom, and has LOTS of info about Dreamybull.

Big prompts dont work

**Comment by mishalhossin** [comment]
try editing utilities\ai_utils.py for more token limit

**Comment by Visionishere** [comment]
i have internet access off currently since that made it wonky, also I dont know how I would go about adding a bigger token limit in the py file

**Comment by mishalhossin** [comment]
> i have internet access off currently since that made it wonky, also I dont know how I would go about adding a bigger token limit in the py file
> 
> I will try simplifying the prompt and see if that works

Just fucking look through it and try to find numbers

**Comment by mishalhossin** [comment]
i will add it to config soon

**Comment by Visionishere** [comment]
> > i have internet access off currently since that made it wonky, also I dont know how I would go about adding a bigger token limit in the py file
> > I will try simplifying the prompt and see if that works
> 
> Just fucking look through it and try to find numbers

ight bro im trying, no need for fruity lang. also good idea with adding it to condig.

**Comment by mishalhossin** [comment]
> ight bro im trying, no need for fruity lang. also good idea with adding it to config.

sorry

**Comment by Visionishere** [comment]
data = {'prompt': prompt, 'max_tokens': 1000, 'temperature': 0.9} seems promising, ill make it 2000 just for fun

**Comment by mishalhossin** [comment]
> ```
> data = {'prompt': prompt, 'max_tokens': 1000, 'temperature': 0.9} seems promising, ill make it 2000 just for fun
> ```

set it to like 4000

**Comment by mishalhossin** [comment]
as its the max

**Comment by Visionishere** [comment]
nada, 
Task exception was never retrieved
future: <Task finished name='Task-19' coro=<on_message.<locals>.generate_response_in_thread() done, defined at C:\Users\Vision\Desktop\gpt4free-discord-main\main.py:138> exception=KeyError('choices')>
Traceback (most recent call last):
  File "C:\Users\Vision\Desktop\gpt4free-discord-main\main.py", line 140, in generate_response_in_thread
    response = await generate_response(prompt)
  File "C:\Users\Vision\Desktop\gpt4free-discord-main\utilities\ai_utils.py", line 62, in generate_response
    return response_data['choices'][0]['text']
KeyError: 'choices'

im just saying "hi" and "hello" btw

**Comment by mishalhossin** [comment]
hmm i guess just stick to 2000 for now

**Comment by Visionishere** [comment]
again idk if the token is just for online search or wha, ill try making the prompt shorter

**Comment by Visionishere** [comment]
worked with AIM, but my prompt causes issues so I think I have my answer. I was glad to inspire a feature however and you were very quick to respond. Have a nice day.

**Comment by mishalhossin** [comment]
> worked with AIM, but my prompt causes issues so I think I have my answer. I was glad to inspire a config tweak however and you were very quick to respond. Have a nice day.

you can also join the [discord](https://discord.gg/xh9MkgeE)
