### ISSUE TITLE
choices, (again)

### ISSUE THREAD

**Issue by Visionishere** [mishalhossin/Discord-AI-Chatbot#152]
Traceback (most recent call last):
  File "/home/runner/HGandH92f239hfuehfjhfi0j2809efhui2ehfuh209efj0i2jer09fj/venv/lib/python3.10/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/runner/HGandH92f239hfuehfjhfi0j2809efhui2ehfuh209efj0i2jer09fj/main.py", line 141, in on_message
    response = await generate_response(instructions, search_results, image_caption, history)
  File "/home/runner/HGandH92f239hfuehfjhfi0j2809efhui2ehfuh209efj0i2jer09fj/utilities/ai_utils.py", line 72, in generate_response
    choices = response_data['choices']
KeyError: 'choices'

internet is disabled

**Comment by Visionishere** [comment]
fixed with install requirements im very retarded
