### ISSUE TITLE
Error sending a PDF file

### ISSUE THREAD

**Issue by PeterDBR27** [mishalhossin/Discord-AI-Chatbot#156]
```py
Traceback (most recent call last):
  File "C:\Users\pedrh\AppData\Local\Programs\Python\Python311\Lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\pedrh\OneDrive\Documentos\Meus Bots\PeterIA\main.py", line 189, in on_message
    response = await generate_response(instructions, search_results, image_caption, history+file_content)
                                                                                    ~~~~~~~^~~~~~~~~~~~~
TypeError: can only concatenate list (not "str") to list
```

**Comment by mishalhossin** [comment]
idk
