### ISSUE TITLE
docx and PendingDeprecationWarning ModuleNotFoundError

### ISSUE THREAD

**Issue by itz-ankit** [mishalhossin/Discord-AI-Chatbot#162]
Traceback (most recent call last):
  File "/home/runner/Discord-AI-Chatbot-2/main.py", line 10, in <module>
    import docx
  File "/home/runner/Discord-AI-Chatbot-2/venv/lib/python3.10/site-packages/docx.py", line 30, in <module>
    from exceptions import PendingDeprecationWarning
ModuleNotFoundError: No module named 'exceptions'

encountering this particular in replit , any idea how to fix this?

**Comment by mishalhossin** [comment]
```
pip install python-docx
```
in the shell

**Comment by itz-ankit** [comment]
> ```
> pip install python-docx
> ```
> 
> in the shell

ah shoot i was doing that in the console lmao , thanks a bunch :)
