### ISSUE TITLE
Env not working cus spelling error

### ISSUE THREAD

**Issue by itz-ankit** [mishalhossin/Discord-AI-Chatbot#192]
Traceback (most recent call last):
  File "/home/runner/Discord-AI-Chatbot-3/venv/lib/python3.10/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/runner/Discord-AI-Chatbot-3/main.py", line 147, in on_message
    response = await asyncio.to_thread(generate_response, instructions=instructions, search=search_results, history=history)
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/runner/Discord-AI-Chatbot-3/utilities/ai_utils.py", line 84, in generate_response
    response = openai.ChatCompletion.create(
  File "/home/runner/Discord-AI-Chatbot-3/venv/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/runner/Discord-AI-Chatbot-3/venv/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 149, in create
    ) = cls.__prepare_create_request(
  File "/home/runner/Discord-AI-Chatbot-3/venv/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 106, in __prepare_create_request
    requestor = api_requestor.APIRequestor(
  File "/home/runner/Discord-AI-Chatbot-3/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 138, in __init__
    self.api_key = key or util.default_api_key()
  File "/home/runner/Discord-AI-Chatbot-3/venv/lib/python3.10/site-packages/openai/util.py", line 186, in default_api_key
    raise openai.error.AuthenticationError(
openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.

**Encountering this specific error and no response from the bot :') any idea ?**

**Comment by elricsilverhandx** [comment]
CHIMERA_GPT_KEY=<YOUR_CHIMIRA_API_KEY>

**Comment by selajuf** [comment]
> env add
> 
> CHIMERA_GPT_KEY=<YOUR_CHIMIRA_API_KEY>

Was inserted in parentheses and without parentheses, gives an error
<img width="895" alt="image" src="https://github.com/mishalhossin/Discord-AI-Chatbot/assets/88133431/8fbf9a7a-9d7b-4c88-b6f1-fa39a9a124d0">

**Comment by harukun-2** [comment]
in ".env":
DISCORD_TOKEN=yourtoken
CHIMERA_GPT_KEY=yourtoken

**Comment by lu5her-s** [comment]
Me added chimera but it error want openai api

**Comment by lu5her-s** [comment]
Ok I see the problem, the variable name change from chimira to chimera it solved for me

**Comment by itz-ankit** [comment]
How many API keys do we have to give ourselves?
even after giving the chimera one it is still showing an api error

**Comment by itz-ankit** [comment]
> Me added chimera but it error want openai api

Same, even after changing the spellings its still not working

**Comment by itz-ankit** [comment]
Traceback (most recent call last):
  File "/home/runner/Discord-AI-Chatbot-mod/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 403, in handle_error_response
    error_data = resp["error"]
KeyError: 'error'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/Discord-AI-Chatbot-mod/venv/lib/python3.10/site-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "/home/runner/Discord-AI-Chatbot-mod/main.py", line 147, in on_message
    response = await asyncio.to_thread(generate_response, instructions=instructions, search=search_results, history=history)
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/runner/Discord-AI-Chatbot-mod/utilities/ai_utils.py", line 84, in generate_response
    response = openai.ChatCompletion.create(
  File "/home/runner/Discord-AI-Chatbot-mod/venv/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/runner/Discord-AI-Chatbot-mod/venv/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/runner/Discord-AI-Chatbot-mod/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/runner/Discord-AI-Chatbot-mod/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/home/runner/Discord-AI-Chatbot-mod/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 763, in _interpret_response_line
    raise self.handle_error_response(
  File "/home/runner/Discord-AI-Chatbot-mod/venv/lib/python3.10/site-packages/openai/api_requestor.py", line 405, in handle_error_response
    raise error.APIError(
openai.error.APIError: Invalid response object from API: '{"detail":"Bad context detected!"}' (HTTP response code was 422)

help :')
