### ISSUE TITLE
Error on pip

### ISSUE THREAD

**Issue by RafeyGx** [mishalhossin/Discord-AI-Chatbot#203]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 147, in on_message
    response = await asyncio.to_thread(generate_response, instructions=instructions, search=search_results, history=history)
AttributeError: module 'asyncio' has no attribute 'to_thread'

**Comment by lu5her-s** [comment]
what version of your python
