### ISSUE TITLE
been having trouble with bot, any time i use: @ it  or use .ask

### ISSUE THREAD

**Issue by harukun-2** [mishalhossin/Discord-AI-Chatbot#217]
[2023-08-06 01:46:29] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Haruku\Desktop\work\sutfff\langucodes\ptyon\Lib\site-packages\openai\api_requestor.py", line 753, in _interpret_response_line
    data = json.loads(rbody)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Haruku\Desktop\work\sutfff\langucodes\ptyon\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haruku\Desktop\work\sutfff\langucodes\ptyon\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haruku\Desktop\work\sutfff\langucodes\ptyon\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Haruku\Desktop\work\sutfff\langucodes\ptyon\Lib\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Haruku\Discord-AI-Chatbot\main.py", line 147, in on_message
    response = await asyncio.to_thread(generate_response, instructions=instructions, search=search_results, history=history)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haruku\Desktop\work\sutfff\langucodes\ptyon\Lib\asyncio\threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haruku\Desktop\work\sutfff\langucodes\ptyon\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haruku\Discord-AI-Chatbot\utilities\ai_utils.py", line 84, in generate_response
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haruku\Desktop\work\sutfff\langucodes\ptyon\Lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haruku\Desktop\work\sutfff\langucodes\ptyon\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haruku\Desktop\work\sutfff\langucodes\ptyon\Lib\site-packages\openai\api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Haruku\Desktop\work\sutfff\langucodes\ptyon\Lib\site-packages\openai\api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\Haruku\Desktop\work\sutfff\langucodes\ptyon\Lib\site-packages\openai\api_requestor.py", line 755, in _interpret_response_line
    raise error.APIError(
openai.error.APIError: HTTP code 404 from API (<!DOCTYPE html><html><head><meta charSet="utf-8"/><meta name="viewport" content="width=device-width"/><title>404: This page could not be found</title><meta name="next-head-count" content="3"/><noscript data-n-css=""></noscript><script defer="" nomodule="" src="/_next/static/chunks/polyfills-78c92fac7aa8fdd8.js"></script><script src="/_next/static/chunks/webpack-3a0131ac78253357.js" defer=""></script><script src="/_next/static/chunks/framework-43665103d101a22d.js" defer=""></script><script src="/_next/static/chunks/main-4ad21330e9300015.js" defer=""></script><script src="/_next/static/chunks/pages/_app-6b79a29ad0d63b21.js" defer=""></script><script src="/_next/static/chunks/pages/_error-a524fad56d7195c8.js" defer=""></script><script src="/_next/static/YDOg3--Wa1tVpHttJePDB/_buildManifest.js" defer=""></script><script src="/_next/static/YDOg3--Wa1tVpHttJePDB/_ssgManifest.js" defer=""></script></head><body><div id="__next"><div style="font-family:system-ui,&quot;Segoe UI&quot;,Roboto,Helvetica,Arial,sans-serif,&quot;Apple Color Emoji&quot;,&quot;Segoe UI Emoji&quot;;height:100vh;text-align:center;display:flex;flex-direction:column;align-items:center;justify-content:center"><div style="line-height:48px"><style>body{color:#000;background:#fff;margin:0}.next-error-h1{border-right:1px solid rgba(0,0,0,.3)}@media (prefers-color-scheme:dark){body{color:#fff;background:#000}.next-error-h1{border-right:1px solid rgba(255,255,255,.3)}}</style><h1 class="next-error-h1" style="display:inline-block;margin:0 20px 0 0;padding-right:23px;font-size:24px;font-weight:500;vertical-align:top">404</h1><div style="display:inline-block"><h2 style="font-size:14px;font-weight:400;line-height:28px">This page could not be found.</h2></div></div></div></div><script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{"statusCode":404}},"page":"/_error","query":{},"buildId":"YDOg3--Wa1tVpHttJePDB","nextExport":true,"isFallback":false,"gip":true,"scriptLoader":[]}</script></body></html>)

**Comment by mishalhossin** [comment]
Api issue

**Comment by harukun-2** [comment]
yep that wat it looks like any idea what i can do?
i have tryed changing models and geting an new key but this error still shows up.

**Comment by SamirXR** [comment]
That's not really a issue of Bot but of Chimera GPT, Their Api is unstable nowadays + It's a recommended to not use Gpt-4 for a while because oof instability, Instead try gpt-3.5-turbo
