### ISSUE TITLE
Error on Replit

### ISSUE THREAD

**Issue by DarthMaus** [mishalhossin/Discord-AI-Chatbot#221]
`discord.client logging in using static token
Traceback (most recent call last):
  File "/home/runner/Discord-AI-Chatbot/main.py", line 507, in <module>
    bot.run(TOKEN)
  File "/home/runner/Discord-AI-Chatbot/venv/lib/python3.10/site-packages/discord/client.py", line 860, in run
    asyncio.run(runner())
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/nix/store/hd4cc9rh83j291r5539hkf6qd8lgiikb-python3-3.10.8/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/runner/Discord-AI-Chatbot/venv/lib/python3.10/site-packages/discord/client.py", line 849, in runner
    await self.start(token, reconnect=reconnect)
  File "/home/runner/Discord-AI-Chatbot/venv/lib/python3.10/site-packages/discord/client.py", line 778, in start
    await self.connect(reconnect=reconnect)
  File "/home/runner/Discord-AI-Chatbot/venv/lib/python3.10/site-packages/discord/client.py", line 704, in connect
    raise PrivilegedIntentsRequired(exc.shard_id) from None
discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.`

How can I fix this

**Comment by DarthMaus** [comment]
forgot to do an important setting
