### ISSUE TITLE
KeyError: 'endpoints'

### ISSUE THREAD

**Issue by matheeshapathirana** [mishalhossin/Discord-AI-Chatbot#242]
I got this error. Please help me to fix this.
```
Looks like the environment variables exists...
Discord Token environment variable is valid
Traceback (most recent call last):
  File "/workspaces/Discord-AI-Chatbot/main.py", line 77, in <module>
    chat_models = fetch_chat_models()
  File "/workspaces/Discord-AI-Chatbot/main.py", line 67, in fetch_chat_models
    models.extend(
  File "/workspaces/Discord-AI-Chatbot/main.py", line 70, in <genexpr>
    if "chat" in model['endpoints'][0]
KeyError: 'endpoints'
```

**Comment by matheeshapathirana** [comment]
I have temporarily fixed the issue by removing `if "chat" in model['endpoints'][0]` from
```
    if response.status_code == 200:
        ModelsData = response.json()
        models.extend(
            model['id']
            for model in ModelsData.get('data')
            if "chat" in model['endpoints'][0]      <--- THIS LINE (Line no. 70)
        )
```
But need a permanent solution

**Comment by L7NEG** [comment]
me too i dont know why this error is started to showing up
