### ISSUE TITLE
i've seen this issue a bit. has there been any workaround or temp fixes?

### ISSUE THREAD

**Issue by ImN3k0** [mishalhossin/Discord-AI-Chatbot#70]
"ChatGPTBot:
[2023-05-15 11:33:50] [ERROR   ] discord.client: Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\ImN3k\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\discord\client.py", line 441, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\ImN3k\Documents\GitHub\Discord-Chatbot-Gpt4Free\main.py", line 143, in on_message
    response = await generate_response(prompt)
  File "C:\Users\ImN3k\Documents\GitHub\Discord-Chatbot-Gpt4Free\main.py", line 39, in generate_response
    response = usesless.Completion.create(prompt=prompt, parentMessageId=message_id)
  File "C:\Users\ImN3k\Documents\GitHub\Discord-Chatbot-Gpt4Free\usesless\__init__.py", line 47, in create
    response = Completion.__response_to_json(content)
  File "C:\Users\ImN3k\Documents\GitHub\Discord-Chatbot-Gpt4Free\usesless\__init__.py", line 54, in __response_to_json
    split_text = text.rsplit("\n", 1)[1]
IndexError: list index out of range"

**Comment by ImN3k0** [comment]
tyvm for you great work and quick fix time :D works like a charm now and haven't experienced any issues even with multiple people driving the AI crazy :P
