### ISSUE TITLE
Command /bonk not working

### ISSUE THREAD

**Issue by EnroXD1** [mishalhossin/Discord-AI-Chatbot#74]
When this command is triggered, the bot simply throws errors into the logs.
![изображение_2023-05-16_163512955](https://github.com/mishalhossin/Discord-AI-Chatbot/assets/49277608/28631325-6f74-478e-acb6-216f182382ae)
Traceback (most recent call last):
  File "/home/runner/DiscordChatbotGpt4Free/venv/lib/python3.10/site-packages/discord/app_commands/commands.py", line 842, in _do_call
    return await self._callback(interaction, **params)  # type: ignore
  File "main.py", line 215, in bonk
    message_history.clear()
NameError: name 'message_history' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/DiscordChatbotGpt4Free/venv/lib/python3.10/site-packages/discord/ext/commands/hybrid.py", line 438, in _invoke_with_namespace
    value = await self._do_call(ctx, ctx.kwargs)  # type: ignore
  File "/home/runner/DiscordChatbotGpt4Free/venv/lib/python3.10/site-packages/discord/app_commands/commands.py", line 860, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'bonk' raised an exception: NameError: name 'message_history' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/DiscordChatbotGpt4Free/venv/lib/python3.10/site-packages/discord/ext/commands/hybrid.py", line 438, in _invoke_with_namespace
    value = await self._do_call(ctx, ctx.kwargs)  # type: ignore
  File "/home/runner/DiscordChatbotGpt4Free/venv/lib/python3.10/site-packages/discord/app_commands/commands.py", line 860, in _do_call
    raise CommandInvokeError(self, e) from e
discord.ext.commands.errors.HybridCommandError: Hybrid command raised an error: Command 'bonk' raised an exception: NameError: name 'message_history' is not defined

**Comment by mishalhossin** [comment]
Due to the implementation of different message storing method for the model, the bonk command will be temporarily removed. This adjustment aims to ensure a more streamlined user experience. Thank you for your understanding

**Comment by mishalhossin** [comment]
Fixed
