### ISSUE TITLE
Error at startup.

### ISSUE THREAD

**Issue by Qiota** [mishalhossin/Discord-AI-Chatbot#98]
Traceback (most recent call last):
  File "/home/runner/Discord-AI-Chatbot/venv/lib/python3.10/site-packages/requests_toolbelt/_compat.py", line 48, in <module>
    from requests.packages.urllib3.contrib import appengine as gaecontrib
ImportError: cannot import name 'appengine' from 'requests.packages.urllib3.contrib' (/home/runner/Discord-AI-Chatbot/venv/lib/python3.10/site-packages/urllib3/contrib/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from imaginepy import AsyncImagine, Style, Ratio
  File "/home/runner/Discord-AI-Chatbot/venv/lib/python3.10/site-packages/imaginepy/__init__.py", line 1, in <module>
    from .sync_imagine import Imagine
  File "/home/runner/Discord-AI-Chatbot/venv/lib/python3.10/site-packages/imaginepy/sync_imagine.py", line 3, in <module>
    from requests_toolbelt.multipart.encoder import MultipartEncoder
  File "/home/runner/Discord-AI-Chatbot/venv/lib/python3.10/site-packages/requests_toolbelt/__init__.py", line 12, in <module>
    from .adapters import SSLAdapter, SourceAddressAdapter
  File "/home/runner/Discord-AI-Chatbot/venv/lib/python3.10/site-packages/requests_toolbelt/adapters/__init__.py", line 12, in <module>
    from .ssl import SSLAdapter
  File "/home/runner/Discord-AI-Chatbot/venv/lib/python3.10/site-packages/requests_toolbelt/adapters/ssl.py", line 16, in <module>
    from .._compat import poolmanager
  File "/home/runner/Discord-AI-Chatbot/venv/lib/python3.10/site-packages/requests_toolbelt/_compat.py", line 50, in <module>
    from urllib3.contrib import appengine as gaecontrib
ImportError: cannot import name 'appengine' from 'urllib3.contrib' (/home/runner/Discord-AI-Chatbot/venv/lib/python3.10/site-packages/urllib3/contrib/__init__.py)

**Comment by mishalhossin** [comment]
@Qiota run `pip install -r requirements` then create a issue
